# sln2make autogenerated Makefile.ag
dir_root=../
dir_tmp=tmp
dir_obj=$(dir_tmp)/obj
dir_lib=lib

all:
	$(MAKE) -C src/vsfilter -f Makefile
	$(MAKE) -C src/subpic -f Makefile
	$(MAKE) -C src/subtitles -f Makefile
	$(MAKE) -C src/dsutil -f Makefile
	$(MAKE) -C src/basevideofilter -f Makefile
	$(MAKE) -C src/subtitles/libssf -f Makefile
	$(MAKE) -C src/BaseClasses -f Makefile
	$(MAKE) -C src/zlib -f Makefile
	$(MAKE) -C src/libpng -f Makefile
	$(MAKE) -C src/luajit -f Makefile


clean:
	$(MAKE) -C src/vsfilter -f Makefile clean
	$(MAKE) -C src/subpic -f Makefile clean
	$(MAKE) -C src/subtitles -f Makefile clean
	$(MAKE) -C src/dsutil -f Makefile clean
	$(MAKE) -C src/basevideofilter -f Makefile clean
	$(MAKE) -C src/subtitles/libssf -f Makefile clean
	$(MAKE) -C src/BaseClasses -f Makefile clean
	$(MAKE) -C src/zlib -f Makefile clean
	$(MAKE) -C src/libpng -f Makefile clean
	$(MAKE) -C src/luajit -f Makefile clean
	rm $(dir_lib)/Release/* bin/Release/*

